title: LvMalware's blog
email: lucas.vieira.ar@disroot.org
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science student, software developer, CTF player and Cyber Security enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: I_Dont_Have_One
github_username:  lvmalware
markdown: kramdown

# Build settings
theme: minima
mathjax: true
#plugins:
#  - jekyll-feed

#

permalink: /:categories/:year/:month/:day/:title:output_ext
