title: LvMalware's blog
email: root@lva.sh
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science major, software developer, CTF player and Cyber Security professional.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lvmalware
github_username:  lvmalware
markdown: kramdown

# Build settings
# theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark

mathjax: true
plugins:
  - jekyll-feed

#

permalink: /:categories/:year/:month/:day/:title:output_ext
